### ISSUE TITLE
扫了一眼一个md文件, 有点问题, 就不pull request了, 你参考修改吧

### ISSUE THREAD

**Issue by sk1418** [intohole/b2#1]
awk 关于使用数组，词典
	-----------------
	+ 数组无初始化 eg. example[1]=1 #example 任意命名 ， 键可以任意设置 ， 数组值也可以 (ok)
	+ 数组循环 ， for(i in example){ example[i] ; #里面的元素}(OK, 但不会保证顺序)
	+ 清空数组 , for(i in example) { delete example[i] ; #循环删除数组元素} (ok, 可以delete(example)删除数组, 以及元素)
	+ 判断数组是否含有这个元素 , if( example[3] ) {} else {} (这个不对, 你这个是判断example[3]的值是不是非零, 当然如果3不存在和ex[3]=0是一样的结果. 正确判断一个key是否存在于数组是if(key in example){...}

**Comment by intohole** [comment]
....你说的那个自动生成的脚本吗？  3 in example , awk 写法 ； 应该说是 词典循环 ， 是没有顺序 我里面使用了 delete example?


谢谢指正
